### ISSUE TITLE
Update snap to 1.0.5

### ISSUE THREAD

**Issue by philipzae** [diddlesnaps/cawbird#3]
Please update to the latest 1.0.5 of cawbird which came out on april 8th.
https://github.com/IBBoard/cawbird/releases

**Comment by diddledan** [comment]
Hi,

Thanks for the prompt. It seems the build was failing due to changes that I hadn't anticipated in snapcraft. I've uploaded a new version of the build configuration, and the autobuilder has just finished and released the updated version.

**Comment by philipzae** [comment]
sweet thanks.

**Comment by philipzae** [comment]
Is there any way you could also have edge branch which builds master each week or two?
