### ISSUE TITLE
Snap 1.1.0-2 fails to start on Mint 20

### ISSUE THREAD

**Issue by gfbett** [diddlesnaps/cawbird#5]
I have the version 1.1.0-2 installed, and when I try to run it I get the following error: 

/snap/cawbird/338/usr/bin/cawbird: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

I've tried refreshing the snap, but I get the same result.

**Comment by diddledan** [comment]
Can you post the output of running the following commands in a terminal, please?

```bash
snap version
snap list cawbird
snap connections cawbird
```

**Comment by gfbett** [comment]
snap version
snap       2.45.3.1
snapd      2.45.3.1
series     16
linuxmint  20
kernel     5.4.0-42-generic


snap list cawbird
Name     Version  Rev  Tracking       Publisher  Notes
cawbird  1.1.0-2  338  latest/stable  diddledan  -

snap connections cawbird
Interface                 Plug                     Slot                             Notes
audio-playback            cawbird:audio-playback   :audio-playback                  -
audio-record              cawbird:audio-record     -                                -
content[gnome-3-28-1804]  cawbird:gnome-3-28-1804  gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     cawbird:gtk-3-themes     gtk-common-themes:gtk-3-themes   -
content[icon-themes]      cawbird:icon-themes      gtk-common-themes:icon-themes    -
content[sound-themes]     cawbird:sound-themes     gtk-common-themes:sound-themes   -
dbus                      -                        cawbird:dbus-cawbird             -
desktop                   cawbird:desktop          :desktop                         -
desktop-legacy            cawbird:desktop-legacy   :desktop-legacy                  -
gsettings                 cawbird:gsettings        :gsettings                       -
home                      cawbird:home             :home                            -
network                   cawbird:network          :network                         -
opengl                    cawbird:opengl           :opengl                          -
pulseaudio                cawbird:pulseaudio       :pulseaudio                      -
unity7                    cawbird:unity7           :unity7                          -
wayland                   cawbird:wayland          :wayland                         -
x11                       cawbird:x11              :x11                             -

**Comment by diddledan** [comment]
Those outputs all look sane and as expected, so I'm unsure what the problem might be just yet... I pushed a new build with revision number 350 a couple of days ago, so you might want to try refreshing again to see if that changes anything...

**Comment by gfbett** [comment]
When I tried refreshing it gave another error (as in this post: https://forum.snapcraft.io/t/gimp-ubuntu-16-04-suddenly-stops-working/18393/2) and after running  sudo /usr/lib/snapd/snap-discard-ns cawbird I could refresh, and now is working. Thanks for the help!
